# -*- coding: utf-8 -*-
"""dataSQLhotel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mrg5cesLcnYyhaAzbl2tUNWpXzje7chD
"""

# ==================================================================================================
# ðŸ“˜ PROYEK AKHIR: PREDIKSI TINGKAT OKUPANSI HOTEL MENGGUNAKAN LSTM
# ==================================================================================================
# Author: Mohamad Haziq Dafren
# Institusi: Politeknik Caltex Riau
# Tujuan: Dokumentasi lengkap proses analisis, cleaning, dan preprocessing data hotel
#         untuk prediksi okupansi menggunakan algoritma LSTM
# ==================================================================================================


# ==================================================================================================
# ðŸ“¦ BLOK 1: Setup Environment & Import Libraries
# ==================================================================================================
"""
Tahap ini melakukan:
- Mount Google Drive untuk akses file SQL
- Import semua library yang dibutuhkan untuk analisis
- Set konfigurasi visualisasi dan display
"""

from google.colab import drive
drive.mount('/content/drive')

# Import libraries untuk data processing
import pandas as pd
import numpy as np
import os
import hashlib
import re
import warnings
from datetime import datetime, timedelta
from collections import defaultdict

# Import libraries untuk visualisasi
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

# Import untuk preprocessing
from sklearn.preprocessing import MinMaxScaler

# Konfigurasi display dan warnings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')

# Konfigurasi style visualisasi
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 10

# Path ke folder data di Google Drive (SESUAIKAN DENGAN FOLDER ANDA!)
file_path = "/content/drive/MyDrive/Data_Hotel/"

print("âœ… Google Drive mounted successfully!")
print(f"ðŸ“‚ Working directory: {file_path}")
print("âœ… All libraries imported successfully!")

# ==================================================================================================
# ðŸ“„ BLOK 2: Identifikasi & Inspeksi File SQL
# ==================================================================================================
"""
Tahap ini melakukan:
- List semua file SQL di folder Data_Hotel
- Tampilkan informasi ukuran file
- Identifikasi file mana yang akan dianalisis
"""

print("=" * 80)
print("ðŸ“„ FILE SQL YANG TERDETEKSI DI FOLDER")
print("=" * 80)

# List semua file SQL
sql_files = []
for filename in os.listdir(file_path):
    if filename.endswith('.sql'):
        filepath = os.path.join(file_path, filename)
        size = os.path.getsize(filepath)
        size_mb = size / (1024 * 1024)
        sql_files.append({
            'filename': filename,
            'path': filepath,
            'size_mb': size_mb
        })

# Tampilkan informasi file
if sql_files:
    print(f"\nâœ… Ditemukan {len(sql_files)} file SQL:\n")
    for idx, f in enumerate(sql_files, 1):
        print(f"{idx}. {f['filename']:<40} | Size: {f['size_mb']:.2f} MB")

    total_size = sum(f['size_mb'] for f in sql_files)
    print(f"\nðŸ“Š Total ukuran: {total_size:.2f} MB")
else:
    print("âš ï¸ Tidak ada file SQL ditemukan di folder!")
    print(f"   Pastikan path benar: {file_path}")

print("=" * 80)

# ==================================================================================================
# ðŸ” BLOK 3: Verifikasi Kesamaan File dengan MD5 Hash
# ==================================================================================================
"""
Tahap ini melakukan:
- Hitung MD5 hash untuk setiap file SQL
- Bandingkan hash untuk verifikasi apakah file identik
- Tentukan file mana yang akan digunakan untuk analisis
"""

def calculate_md5(filepath, chunk_size=8192):
    """
    Hitung MD5 hash dari file dengan membaca chunk by chunk.
    Metode ini efisien untuk file berukuran besar (ratusan MB).

    Args:
        filepath: Path lengkap ke file
        chunk_size: Ukuran chunk untuk dibaca (default 8KB)

    Returns:
        MD5 hash string (32 karakter hexadecimal)
    """
    md5 = hashlib.md5()
    with open(filepath, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            md5.update(chunk)
    return md5.hexdigest()


print("=" * 80)
print("ðŸ” VERIFIKASI KESAMAAN FILE DENGAN MD5 HASH")
print("=" * 80)
print("\nâ³ Menghitung MD5 hash untuk setiap file...")
print("   (Proses ini membutuhkan waktu ~30-60 detik per file)\n")

# Hitung MD5 untuk setiap file
hash_results = []
for i, sql_file in enumerate(sql_files, 1):
    print(f"[{i}/{len(sql_files)}] Processing: {sql_file['filename']}")
    start_time = datetime.now()

    md5_hash = calculate_md5(sql_file['path'])

    elapsed = (datetime.now() - start_time).total_seconds()
    hash_results.append({
        'filename': sql_file['filename'],
        'size_mb': sql_file['size_mb'],
        'md5_hash': md5_hash,
        'time_seconds': elapsed
    })

    print(f"    MD5: {md5_hash}")
    print(f"    Time: {elapsed:.2f} seconds\n")

# Buat DataFrame untuk comparison
hash_df = pd.DataFrame(hash_results)

# Analisis hasil
print("=" * 80)
print("ðŸ“Š HASIL VERIFIKASI MD5 HASH")
print("=" * 80)

unique_hashes = hash_df['md5_hash'].nunique()

if unique_hashes == 1:
    print("\nâœ… VERIFIED: Semua file IDENTIK (100% sama)!")
    print(f"\nðŸ“Œ MD5 Hash: {hash_df['md5_hash'].iloc[0]}")
    print("\nðŸ’¡ Kesimpulan:")
    print("   â€¢ Ketiga file (E, M, N) adalah backup yang sama persis")
    print("   â€¢ Isi data, struktur, dan urutan record 100% identik")
    print("   â€¢ Untuk analisis, cukup gunakan 1 file saja")
    print("   â€¢ File lain berfungsi sebagai redundansi/backup")

    # Pilih file yang akan digunakan (biasanya file M atau yang paling baru)
    selected_file = None
    for f in sql_files:
        if 'M ' in f['filename']:
            selected_file = f
            break
    if not selected_file:
        selected_file = sql_files[0]

    print(f"\nðŸŽ¯ File yang dipilih untuk analisis: {selected_file['filename']}")

else:
    print(f"\nâš ï¸ WARNING: File TIDAK identik!")
    print(f"   Ditemukan {unique_hashes} hash berbeda\n")
    print("ðŸ“‹ Detail per file:")
    for idx, row in hash_df.iterrows():
        print(f"   {row['filename']}: {row['md5_hash']}")
    print("\nâš ï¸ Perlu investigasi lebih lanjut sebelum melanjutkan!")

# Tampilkan tabel summary
print("\n" + "=" * 80)
print("ðŸ“‹ SUMMARY TABLE")
print("=" * 80)
print(hash_df[['filename', 'size_mb', 'md5_hash']].to_string(index=False))
print("=" * 80)

# ==================================================================================================
# ðŸ“¥ BLOK 4: Load & Parse Data dari SQL File
# ==================================================================================================
"""
Tahap ini melakukan:
- Baca file SQL yang dipilih
- Extract nama kolom dari INSERT statement
- Parse INSERT statements untuk extract data
- Convert ke pandas DataFrame
- Filter data room_transaction dengan kriteria:
  * Code_Transaction = 'R01' (Room Charge)
  * DC = 'D' (Debit/charge to guest)
  * Date >= 2021-01-01
"""

print("=" * 80)
print("ðŸ“¥ LOADING DATA DARI SQL FILE")
print("=" * 80)

# Step 1: Extract column names dari INSERT statement
def extract_column_names(filepath, table_name='room_transaction'):
    """
    Extract nama kolom yang digunakan di INSERT statement.

    Args:
        filepath: Path ke file SQL
        table_name: Nama tabel yang akan di-parse

    Returns:
        List of column names
    """
    print(f"\nðŸ” Extracting column names from INSERT statement...")

    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            if f'INSERT INTO `{table_name}`' in line:
                # Extract kolom dari pattern: INSERT INTO `table` (`col1`,`col2`,...)
                cols_match = re.search(r'INSERT INTO `' + table_name + r'`\s*\(([^)]+)\)', line)
                if cols_match:
                    cols_text = cols_match.group(1)
                    # Extract nama kolom (remove backticks)
                    column_names = [col.strip().strip('`') for col in cols_text.split(',')]
                    print(f"   âœ… Found {len(column_names)} columns in INSERT statement")
                    return column_names

    print("   âš ï¸ Could not find column names in INSERT statement")
    return None

# Step 2: Parse SQL INSERT statements
def parse_sql_inserts(filepath, table_name='room_transaction'):
    """
    Parse INSERT statements dari file SQL dan convert ke list of tuples.

    Args:
        filepath: Path ke file SQL
        table_name: Nama tabel yang akan di-parse

    Returns:
        Tuple: (list of data rows, number of columns)
    """
    data_rows = []
    num_columns = None

    print(f"\nâ³ Reading file: {os.path.basename(filepath)}")
    print("   Parsing INSERT statements...\n")

    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        current_insert = None
        line_count = 0

        for line in f:
            line_count += 1

            # Cari baris INSERT INTO
            if f'INSERT INTO `{table_name}`' in line:
                current_insert = line.strip()
                continue

            # Jika sedang membaca INSERT statement
            if current_insert:
                current_insert += ' ' + line.strip()

                # Cek apakah INSERT statement sudah selesai (diakhiri dengan ;)
                if line.strip().endswith(';'):
                    # Extract values menggunakan regex
                    # Pattern: VALUES (...),(...),(...)...;
                    values_section = re.search(r'VALUES\s+(.+);', current_insert)
                    if values_section:
                        values_text = values_section.group(1)

                        # Split by '),(' untuk pisahkan setiap row
                        rows = re.findall(r'\(([^)]+)\)', values_text)

                        for row in rows:
                            # Parse setiap field dalam row
                            # Handle NULL, string dengan quotes, dan numeric values
                            fields = []
                            current_field = ''
                            in_quotes = False

                            for char in row + ',':
                                if char == "'" and (not current_field or current_field[-1] != '\\'):
                                    in_quotes = not in_quotes
                                elif char == ',' and not in_quotes:
                                    field = current_field.strip()
                                    if field == 'NULL':
                                        fields.append(None)
                                    elif field.startswith("'") and field.endswith("'"):
                                        fields.append(field[1:-1])
                                    else:
                                        try:
                                            # Try convert to number
                                            if '.' in field:
                                                fields.append(float(field))
                                            else:
                                                fields.append(int(field))
                                        except:
                                            fields.append(field)
                                    current_field = ''
                                else:
                                    current_field += char

                            data_rows.append(tuple(fields))

                            # Get number of columns from first row
                            if num_columns is None:
                                num_columns = len(fields)

                    current_insert = None

            # Progress indicator setiap 100K baris
            if line_count % 100000 == 0:
                print(f"   Processed {line_count:,} lines... ({len(data_rows):,} data rows extracted)")

    print(f"\nâœ… Parsing complete!")
    print(f"   Total lines processed: {line_count:,}")
    print(f"   Total data rows extracted: {len(data_rows):,}")
    print(f"   Number of columns per row: {num_columns}")

    return data_rows, num_columns

# Extract column names from INSERT statement
column_names = extract_column_names(selected_file['path'])

# Parse data dari file yang dipilih
data_rows, num_cols = parse_sql_inserts(selected_file['path'])

# Verify column count
if column_names and len(column_names) != num_cols:
    print(f"\nâš ï¸ Warning: Column count mismatch!")
    print(f"   Columns in INSERT: {len(column_names)}")
    print(f"   Columns in data: {num_cols}")
    print("   Using generic column names...")
    column_names = [f'Col_{i}' for i in range(num_cols)]
elif not column_names:
    print(f"\nâš ï¸ Column names not found in INSERT statement")
    print("   Using generic column names...")
    column_names = [f'Col_{i}' for i in range(num_cols)]

print(f"\nðŸ“‹ Column names being used ({len(column_names)} columns):")
for i, col in enumerate(column_names):
    print(f"   {i:2d}. {col}")

# Create DataFrame
df_raw = pd.DataFrame(data_rows, columns=column_names)

print("\n" + "=" * 80)
print("ðŸ“Š RAW DATA LOADED")
print("=" * 80)
print(f"Shape: {df_raw.shape[0]:,} rows Ã— {df_raw.shape[1]} columns")
print("\nðŸ‘€ Preview 5 baris pertama:")
print(df_raw.head())

# ==================================================================================================
# ðŸ”¬ BLOK 5: Initial Data Exploration
# ==================================================================================================
"""
Tahap ini melakukan:
- Inspeksi tipe data setiap kolom
- Cek missing values
- Analisis distribusi tahun dan bulan
- Identifikasi nilai unik untuk kolom kategorikal penting
"""

print("\n" + "=" * 80)
print("ðŸ”¬ INITIAL DATA EXPLORATION")
print("=" * 80)

# Info tipe data
print("\nðŸ“‹ Informasi Tipe Data:")
print("-" * 80)
df_raw.info()

# Missing values
print("\n" + "=" * 80)
print("â“ MISSING VALUES ANALYSIS")
print("=" * 80)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw)) * 100
missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing_Count': missing.values,
    'Missing_Percentage': missing_pct.values
})
missing_df = missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)

if len(missing_df) > 0:
    print("\nâš ï¸ Kolom dengan missing values:")
    print(missing_df.to_string(index=False))
else:
    print("\nâœ… Tidak ada missing values!")

# Identifikasi kolom penting berdasarkan nama atau posisi
# Cari kolom yang mirip dengan nama yang diharapkan
def find_column(df, possible_names):
    """Find column by matching possible names (case-insensitive)"""
    for col in df.columns:
        for name in possible_names:
            if name.lower() in col.lower():
                return col
    return None

# Map kolom penting
col_roomno = find_column(df_raw, ['RoomNo', 'room', 'kamar'])
col_type = find_column(df_raw, ['Type', 'tipe'])
col_code = find_column(df_raw, ['Code_Transaction', 'code', 'kode'])
col_dc = find_column(df_raw, ['DC', 'debit_credit'])
col_debet = find_column(df_raw, ['Debet', 'debit', 'amount'])
col_date = find_column(df_raw, ['Date', 'tanggal', 'TransactionDate'])

print("\n" + "=" * 80)
print("ðŸ” IDENTIFIED KEY COLUMNS")
print("=" * 80)
print(f"   Room Number: {col_roomno}")
print(f"   Room Type: {col_type}")
print(f"   Transaction Code: {col_code}")
print(f"   DC (Debit/Credit): {col_dc}")
print(f"   Debet Amount: {col_debet}")
print(f"   Date: {col_date}")

# Analisis kolom-kolom penting
print("\n" + "=" * 80)
print("ðŸ”‘ ANALISIS KOLOM KUNCI")
print("=" * 80)

if col_type:
    print("\n1ï¸âƒ£ Tipe Kamar (Type):")
    print(df_raw[col_type].value_counts())

if col_code:
    print("\n2ï¸âƒ£ Kode Transaksi (Code_Transaction) - Top 10:")
    print(df_raw[col_code].value_counts().head(10))

if col_dc:
    print("\n3ï¸âƒ£ Debit/Credit (DC):")
    print(df_raw[col_dc].value_counts())

# Convert Date ke datetime untuk analisis temporal
if col_date:
    df_raw[col_date] = pd.to_datetime(df_raw[col_date], errors='coerce')

    print("\n4ï¸âƒ£ Rentang Tanggal Data:")
    print(f"   Earliest: {df_raw[col_date].min()}")
    print(f"   Latest: {df_raw[col_date].max()}")
    print(f"   Span: {(df_raw[col_date].max() - df_raw[col_date].min()).days} days")

    # Distribusi per tahun
    print("\n5ï¸âƒ£ Distribusi Data per Tahun:")
    year_dist = df_raw[col_date].dt.year.value_counts().sort_index()
    print(year_dist)
else:
    print("\nâš ï¸ Warning: Date column not found!")

# ==================================================================================================
# ðŸŽ¯ BLOK 6: Filter Data untuk Analisis Okupansi
# ==================================================================================================
"""
Tahap ini melakukan:
- Filter hanya Room Charge transactions (R01)
- Filter hanya Debit transactions (D)
- Filter periode 2021-2025
- Remove data yang tidak valid
"""

print("\n" + "=" * 80)
print("ðŸŽ¯ FILTERING DATA UNTUK ANALISIS OKUPANSI")
print("=" * 80)

# Pastikan kolom penting sudah teridentifikasi
if not all([col_roomno, col_type, col_code, col_dc, col_debet, col_date]):
    print("\nâš ï¸ ERROR: Tidak semua kolom penting teridentifikasi!")
    print("   Tidak dapat melanjutkan filtering.")
    print("\nðŸ“‹ Status kolom:")
    print(f"   RoomNo: {'âœ…' if col_roomno else 'âŒ'} {col_roomno}")
    print(f"   Type: {'âœ…' if col_type else 'âŒ'} {col_type}")
    print(f"   Code: {'âœ…' if col_code else 'âŒ'} {col_code}")
    print(f"   DC: {'âœ…' if col_dc else 'âŒ'} {col_dc}")
    print(f"   Debet: {'âœ…' if col_debet else 'âŒ'} {col_debet}")
    print(f"   Date: {'âœ…' if col_date else 'âŒ'} {col_date}")
else:
    print("\nâœ… Semua kolom penting berhasil diidentifikasi")
    print("\nðŸ“Œ Kriteria filtering:")
    print(f"   1. {col_code} = 'R01' (Room Charge only)")
    print(f"   2. {col_dc} = 'D' (Debit transactions only)")
    print(f"   3. {col_date} >= 2021-01-01 (Fokus periode 2021-2025)")
    print("   4. Remove null values di kolom penting")

    # Filter step by step dengan tracking
    print("\nðŸ”„ Proses filtering:")
    print(f"   Starting rows: {len(df_raw):,}")

    # Filter 1: Room Charge only
    df_filtered = df_raw[df_raw[col_code] == 'R01'].copy()
    print(f"   After R01 filter: {len(df_filtered):,} rows ({len(df_filtered)/len(df_raw)*100:.1f}%)")

    # Filter 2: Debit only
    df_filtered = df_filtered[df_filtered[col_dc] == 'D'].copy()
    print(f"   After Debit filter: {len(df_filtered):,} rows ({len(df_filtered)/len(df_raw)*100:.1f}%)")

    # Filter 3: Date range
    df_filtered = df_filtered[df_filtered[col_date] >= '2021-01-01'].copy()
    print(f"   After date filter: {len(df_filtered):,} rows ({len(df_filtered)/len(df_raw)*100:.1f}%)")

    # Filter 4: Remove null values di kolom penting
    cols_required = [col_roomno, col_type, col_debet, col_date]
    df_filtered = df_filtered.dropna(subset=cols_required)
    print(f"   After null removal: {len(df_filtered):,} rows ({len(df_filtered)/len(df_raw)*100:.1f}%)")

    # Sort by date
    df_filtered = df_filtered.sort_values(col_date).reset_index(drop=True)

    print("\nâœ… Filtering complete!")
    print(f"ðŸ“Š Final dataset: {len(df_filtered):,} rows Ã— {len(df_filtered.columns)} columns")

    print("\nðŸ‘€ Preview filtered data:")
    preview_cols = [col_date, col_roomno, col_type, col_debet]
    if 'Description' in df_filtered.columns:
        preview_cols.append('Description')
    print(df_filtered[preview_cols].head(10))

# ==================================================================================================
# ðŸ“Š BLOK 7: EXPLORATORY DATA ANALYSIS (EDA) - EXTENDED VERSION
# ==================================================================================================
"""
Tahap EDA yang komprehensif dengan berbagai visualisasi untuk memahami:
- Pola temporal (tren, seasonality, cyclical patterns)
- Distribusi revenue dan okupansi
- Perbandingan tipe kamar
- Korelasi antar variabel
- Outliers dan anomali
"""

print("\n" + "=" * 80)
print("ðŸ“Š EXPLORATORY DATA ANALYSIS (EDA)")
print("=" * 80)

# Agregasi data harian untuk analisis
print("\nâ³ Agregasi data per hari...")

df_filtered['Year'] = df_filtered[col_date].dt.year
df_filtered['Month'] = df_filtered[col_date].dt.month
df_filtered['Day'] = df_filtered[col_date].dt.day
df_filtered['DayOfWeek'] = df_filtered[col_date].dt.day_name()
df_filtered['DayOfWeek_Num'] = df_filtered[col_date].dt.dayofweek

# Agregasi harian
daily_agg = df_filtered.groupby(col_date).agg({
    col_roomno: 'nunique',  # Jumlah kamar unik yang terjual
    col_debet: 'sum',  # Total revenue
    col_type: 'count'  # Total transaksi
}).reset_index()

daily_agg.columns = ['Tanggal', 'Kamar_Terjual', 'Revenue', 'Jumlah_Transaksi']

# Hitung okupansi rate (asumsi total kamar = 58)
TOTAL_ROOMS = 58
daily_agg['Okupansi_Rate'] = (daily_agg['Kamar_Terjual'] / TOTAL_ROOMS) * 100

# Agregasi per tipe kamar per hari
room_type_daily = df_filtered.groupby([col_date, col_type]).agg({
    col_roomno: 'nunique'
}).reset_index()
room_type_daily.columns = ['Tanggal', 'Tipe', 'Jumlah']

# Pivot untuk mendapat kolom per tipe kamar
room_type_pivot = room_type_daily.pivot(index='Tanggal', columns='Tipe', values='Jumlah').fillna(0).reset_index()
room_type_pivot.columns.name = None

# Merge dengan daily_agg
daily_data = daily_agg.merge(room_type_pivot, on='Tanggal', how='left').fillna(0)

# Rename kolom tipe kamar jika ada
type_mapping = {}
for col in room_type_pivot.columns:
    if col != 'Tanggal':
        type_mapping[col] = f'Kamar_{col}'
daily_data = daily_data.rename(columns=type_mapping)

# Ensure all room types exist (STD, SPR, FMY, JS)
for col in ['Kamar_STD', 'Kamar_SPR', 'Kamar_FMY', 'Kamar_JS']:
    if col not in daily_data.columns:
        daily_data[col] = 0

# Extract temporal features
daily_data['Tahun'] = pd.to_datetime(daily_data['Tanggal']).dt.year
daily_data['Bulan'] = pd.to_datetime(daily_data['Tanggal']).dt.month
daily_data['Hari'] = pd.to_datetime(daily_data['Tanggal']).dt.day_name()
daily_data['Hari_Numeric'] = pd.to_datetime(daily_data['Tanggal']).dt.dayofweek

# Reorder columns
final_columns = [
    'Tanggal', 'Tahun', 'Bulan', 'Hari', 'Hari_Numeric',
    'Kamar_Terjual', 'Revenue', 'Okupansi_Rate',
    'Kamar_STD', 'Kamar_SPR', 'Kamar_FMY', 'Kamar_JS'
]
daily_data = daily_data[final_columns]

print(f"âœ… Data agregasi harian siap: {len(daily_data)} hari")
print("\nðŸ‘€ Preview:")
print(daily_data.head(10))

# ==================== VISUALISASI 1: Tren Okupansi Rate =====================
print("\n" + "=" * 80)
print("ðŸ“ˆ VISUALISASI 1: Tren Okupansi Rate Over Time")
print("=" * 80)

fig, ax = plt.subplots(figsize=(16, 6))

ax.plot(daily_data['Tanggal'], daily_data['Okupansi_Rate'],
        linewidth=1.5, color='#2E86AB', alpha=0.8)
ax.fill_between(daily_data['Tanggal'], daily_data['Okupansi_Rate'],
                alpha=0.3, color='#2E86AB')

# Moving average untuk melihat tren
ma_30 = daily_data['Okupansi_Rate'].rolling(window=30, center=True).mean()
ax.plot(daily_data['Tanggal'], ma_30,
        linewidth=2.5, color='#A23B72', label='30-Day Moving Average', alpha=0.9)

ax.axhline(y=daily_data['Okupansi_Rate'].mean(),
          color='#F18F01', linestyle='--', linewidth=2, label=f'Mean: {daily_data["Okupansi_Rate"].mean():.1f}%')

ax.set_xlabel('Tanggal', fontsize=12, fontweight='bold')
ax.set_ylabel('Okupansi Rate (%)', fontsize=12, fontweight='bold')
ax.set_title('Tren Okupansi Hotel (2021-2025)\ndengan 30-Day Moving Average',
            fontsize=14, fontweight='bold', pad=20)
ax.legend(loc='best', fontsize=10)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print(f"ðŸ“Š Statistik Okupansi Rate:")
print(f"   Mean: {daily_data['Okupansi_Rate'].mean():.2f}%")
print(f"   Median: {daily_data['Okupansi_Rate'].median():.2f}%")
print(f"   Std Dev: {daily_data['Okupansi_Rate'].std():.2f}%")
print(f"   Min: {daily_data['Okupansi_Rate'].min():.2f}%")
print(f"   Max: {daily_data['Okupansi_Rate'].max():.2f}%")

# ==================== VISUALISASI 2: Tren Revenue ============================
print("\n" + "=" * 80)
print("ðŸ’° VISUALISASI 2: Tren Revenue Over Time")
print("=" * 80)

fig, ax = plt.subplots(figsize=(16, 6))

ax.plot(daily_data['Tanggal'], daily_data['Revenue'],
        linewidth=1.2, color='#F18F01', alpha=0.7)
ax.fill_between(daily_data['Tanggal'], daily_data['Revenue'],
                alpha=0.2, color='#F18F01')

# Moving average
ma_30_rev = daily_data['Revenue'].rolling(window=30, center=True).mean()
ax.plot(daily_data['Tanggal'], ma_30_rev,
        linewidth=2.5, color='#C73E1D', label='30-Day Moving Average', alpha=0.9)

ax.axhline(y=daily_data['Revenue'].mean(),
          color='#2E86AB', linestyle='--', linewidth=2,
          label=f'Mean: Rp {daily_data["Revenue"].mean():,.0f}')

ax.set_xlabel('Tanggal', fontsize=12, fontweight='bold')
ax.set_ylabel('Revenue (Rp)', fontsize=12, fontweight='bold')
ax.set_title('Tren Revenue Hotel (2021-2025)', fontsize=14, fontweight='bold', pad=20)
ax.legend(loc='best', fontsize=10)
ax.grid(True, alpha=0.3)

# Format y-axis untuk currency
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'Rp {x/1e6:.1f}M'))

plt.tight_layout()
plt.show()

print(f"ðŸ“Š Statistik Revenue:")
print(f"   Mean: Rp {daily_data['Revenue'].mean():,.0f}")
print(f"   Median: Rp {daily_data['Revenue'].median():,.0f}")
print(f"   Total: Rp {daily_data['Revenue'].sum():,.0f}")
print(f"   Min: Rp {daily_data['Revenue'].min():,.0f}")
print(f"   Max: Rp {daily_data['Revenue'].max():,.0f}")

# ==================== VISUALISASI 3: Distribusi Okupansi & Revenue ===========
print("\n" + "=" * 80)
print("ðŸ“Š VISUALISASI 3: Distribusi Okupansi Rate & Revenue")
print("=" * 80)

fig, axes = plt.subplots(2, 2, figsize=(16, 10))

# Histogram Okupansi Rate
axes[0, 0].hist(daily_data['Okupansi_Rate'], bins=30, color='#2E86AB', alpha=0.7, edgecolor='black')
axes[0, 0].axvline(daily_data['Okupansi_Rate'].mean(), color='#C73E1D', linestyle='--', linewidth=2, label='Mean')
axes[0, 0].axvline(daily_data['Okupansi_Rate'].median(), color='#F18F01', linestyle='--', linewidth=2, label='Median')
axes[0, 0].set_xlabel('Okupansi Rate (%)', fontweight='bold')
axes[0, 0].set_ylabel('Frequency', fontweight='bold')
axes[0, 0].set_title('Distribusi Okupansi Rate', fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Boxplot Okupansi Rate
axes[0, 1].boxplot(daily_data['Okupansi_Rate'], vert=True, patch_artist=True,
                   boxprops=dict(facecolor='#2E86AB', alpha=0.7),
                   medianprops=dict(color='#C73E1D', linewidth=2))
axes[0, 1].set_ylabel('Okupansi Rate (%)', fontweight='bold')
axes[0, 1].set_title('Boxplot Okupansi Rate\n(Mendeteksi Outliers)', fontweight='bold')
axes[0, 1].grid(True, alpha=0.3, axis='y')

# Histogram Revenue
axes[1, 0].hist(daily_data['Revenue'], bins=30, color='#F18F01', alpha=0.7, edgecolor='black')
axes[1, 0].axvline(daily_data['Revenue'].mean(), color='#C73E1D', linestyle='--', linewidth=2, label='Mean')
axes[1, 0].axvline(daily_data['Revenue'].median(), color='#2E86AB', linestyle='--', linewidth=2, label='Median')
axes[1, 0].set_xlabel('Revenue (Rp)', fontweight='bold')
axes[1, 0].set_ylabel('Frequency', fontweight='bold')
axes[1, 0].set_title('Distribusi Revenue', fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x/1e6:.1f}M'))

# Boxplot Revenue
axes[1, 1].boxplot(daily_data['Revenue'], vert=True, patch_artist=True,
                   boxprops=dict(facecolor='#F18F01', alpha=0.7),
                   medianprops=dict(color='#C73E1D', linewidth=2))
axes[1, 1].set_ylabel('Revenue (Rp)', fontweight='bold')
axes[1, 1].set_title('Boxplot Revenue\n(Mendeteksi Outliers)', fontweight='bold')
axes[1, 1].grid(True, alpha=0.3, axis='y')
axes[1, 1].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x/1e6:.1f}M'))

plt.tight_layout()
plt.show()

# ==================== VISUALISASI 4: Pola Mingguan (Day of Week) =============
print("\n" + "=" * 80)
print("ðŸ“… VISUALISASI 4: Pola Okupansi per Hari dalam Seminggu")
print("=" * 80)

# Agregasi per hari dalam seminggu
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekly_pattern = daily_data.groupby('Hari').agg({
    'Okupansi_Rate': 'mean',
    'Revenue': 'mean',
    'Kamar_Terjual': 'mean'
}).reindex(day_order)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Bar chart Okupansi
axes[0].bar(range(7), weekly_pattern['Okupansi_Rate'],
           color=['#2E86AB' if i < 5 else '#F18F01' for i in range(7)], alpha=0.8)
axes[0].set_xticks(range(7))
axes[0].set_xticklabels(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], rotation=0)
axes[0].set_ylabel('Rata-rata Okupansi Rate (%)', fontweight='bold')
axes[0].set_title('Rata-rata Okupansi per Hari dalam Seminggu', fontweight='bold')
axes[0].grid(True, alpha=0.3, axis='y')
axes[0].axhline(y=weekly_pattern['Okupansi_Rate'].mean(), color='#C73E1D',
               linestyle='--', linewidth=2, label='Weekly Average')
axes[0].legend()

# Bar chart Revenue
axes[1].bar(range(7), weekly_pattern['Revenue']/1e6,
           color=['#2E86AB' if i < 5 else '#F18F01' for i in range(7)], alpha=0.8)
axes[1].set_xticks(range(7))
axes[1].set_xticklabels(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], rotation=0)
axes[1].set_ylabel('Rata-rata Revenue (Juta Rp)', fontweight='bold')
axes[1].set_title('Rata-rata Revenue per Hari dalam Seminggu', fontweight='bold')
axes[1].grid(True, alpha=0.3, axis='y')
axes[1].axhline(y=weekly_pattern['Revenue'].mean()/1e6, color='#C73E1D',
               linestyle='--', linewidth=2, label='Weekly Average')
axes[1].legend()

plt.tight_layout()
plt.show()

print("ðŸ“Š Statistik per Hari:")
print(weekly_pattern.round(2))

# ==================== VISUALISASI 5: Pola Bulanan ============================
print("\n" + "=" * 80)
print("ðŸ“† VISUALISASI 5: Pola Okupansi & Revenue per Bulan")
print("=" * 80)

# Agregasi per bulan
monthly_pattern = daily_data.groupby('Bulan').agg({
    'Okupansi_Rate': 'mean',
    'Revenue': 'mean',
    'Kamar_Terjual': 'mean'
})

month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Line chart Okupansi
axes[0].plot(monthly_pattern.index, monthly_pattern['Okupansi_Rate'],
            marker='o', linewidth=2.5, markersize=8, color='#2E86AB')
axes[0].fill_between(monthly_pattern.index, monthly_pattern['Okupansi_Rate'],
                     alpha=0.3, color='#2E86AB')
axes[0].set_xticks(range(1, 13))
axes[0].set_xticklabels(month_names)
axes[0].set_ylabel('Rata-rata Okupansi Rate (%)', fontweight='bold')
axes[0].set_title('Pola Okupansi Bulanan (Rata-rata 2021-2025)', fontweight='bold')
axes[0].grid(True, alpha=0.3)
axes[0].axhline(y=monthly_pattern['Okupansi_Rate'].mean(), color='#C73E1D',
               linestyle='--', linewidth=2, label='Overall Average')
axes[0].legend()

# Line chart Revenue
axes[1].plot(monthly_pattern.index, monthly_pattern['Revenue']/1e6,
            marker='s', linewidth=2.5, markersize=8, color='#F18F01')
axes[1].fill_between(monthly_pattern.index, monthly_pattern['Revenue']/1e6,
                     alpha=0.3, color='#F18F01')
axes[1].set_xticks(range(1, 13))
axes[1].set_xticklabels(month_names)
axes[1].set_ylabel('Rata-rata Revenue (Juta Rp)', fontweight='bold')
axes[1].set_title('Pola Revenue Bulanan (Rata-rata 2021-2025)', fontweight='bold')
axes[1].grid(True, alpha=0.3)
axes[1].axhline(y=monthly_pattern['Revenue'].mean()/1e6, color='#C73E1D',
               linestyle='--', linewidth=2, label='Overall Average')
axes[1].legend()

plt.tight_layout()
plt.show()

print("ðŸ“Š Statistik per Bulan:")
print(monthly_pattern.round(2))

# ==================== VISUALISASI 6: Perbandingan Tipe Kamar ================
print("\n" + "=" * 80)
print("ðŸ¨ VISUALISASI 6: Distribusi & Performa Tipe Kamar")
print("=" * 80)

# Total penjualan per tipe kamar
room_totals = {
    'STD': daily_data['Kamar_STD'].sum(),
    'SPR': daily_data['Kamar_SPR'].sum(),
    'FMY': daily_data['Kamar_FMY'].sum(),
    'JS': daily_data['Kamar_JS'].sum()
}

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Pie chart distribusi
colors = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']
axes[0].pie(room_totals.values(), labels=room_totals.keys(), autopct='%1.1f%%',
           colors=colors, startangle=90, textprops={'fontsize': 12, 'fontweight': 'bold'})
axes[0].set_title('Distribusi Penjualan Kamar per Tipe\n(Total 2021-2025)',
                 fontweight='bold', fontsize=13)

# Bar chart perbandingan
room_types = list(room_totals.keys())
room_counts = list(room_totals.values())
axes[1].bar(room_types, room_counts, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
axes[1].set_xlabel('Tipe Kamar', fontweight='bold', fontsize=12)
axes[1].set_ylabel('Total Kamar Terjual', fontweight='bold', fontsize=12)
axes[1].set_title('Perbandingan Total Penjualan per Tipe Kamar', fontweight='bold', fontsize=13)
axes[1].grid(True, alpha=0.3, axis='y')

# Add value labels on bars
for i, v in enumerate(room_counts):
    axes[1].text(i, v + max(room_counts)*0.01, f'{int(v):,}',
                ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

print("ðŸ“Š Total Penjualan per Tipe Kamar:")
for room_type, count in room_totals.items():
    pct = (count / sum(room_totals.values())) * 100
    print(f"   {room_type}: {count:,.0f} kamar ({pct:.1f}%)")

# ==================== VISUALISASI 7: Heatmap Korelasi ======================
print("\n" + "=" * 80)
print("ðŸ”— VISUALISASI 7: Correlation Heatmap")
print("=" * 80)

# Pilih kolom numerik untuk korelasi
corr_cols = ['Kamar_Terjual', 'Revenue', 'Okupansi_Rate',
             'Kamar_STD', 'Kamar_SPR', 'Kamar_FMY', 'Kamar_JS']
corr_matrix = daily_data[corr_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,
           square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Correlation Heatmap - Variabel Utama', fontweight='bold', fontsize=14, pad=20)
plt.tight_layout()
plt.show()

print("ðŸ“Š Korelasi dengan Okupansi Rate:")
okupansi_corr = corr_matrix['Okupansi_Rate'].sort_values(ascending=False)
print(okupansi_corr)

# ==================== VISUALISASI 8: Yearly Comparison =======================
print("\n" + "=" * 80)
print("ðŸ“Š VISUALISASI 8: Perbandingan Performa Tahunan")
print("=" * 80)

# Agregasi per tahun
yearly_stats = daily_data.groupby('Tahun').agg({
    'Okupansi_Rate': 'mean',
    'Revenue': 'sum',
    'Kamar_Terjual': 'sum'
}).round(2)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Average Okupansi per Year
axes[0].bar(yearly_stats.index, yearly_stats['Okupansi_Rate'],
           color='#2E86AB', alpha=0.8, edgecolor='black')
axes[0].set_xlabel('Tahun', fontweight='bold')
axes[0].set_ylabel('Rata-rata Okupansi Rate (%)', fontweight='bold')
axes[0].set_title('Rata-rata Okupansi Rate per Tahun', fontweight='bold')
axes[0].grid(True, alpha=0.3, axis='y')
for i, v in enumerate(yearly_stats['Okupansi_Rate']):
    axes[0].text(yearly_stats.index[i], v + 1, f'{v:.1f}%', ha='center', fontweight='bold')

# Total Revenue per Year
axes[1].bar(yearly_stats.index, yearly_stats['Revenue']/1e9,
           color='#F18F01', alpha=0.8, edgecolor='black')
axes[1].set_xlabel('Tahun', fontweight='bold')
axes[1].set_ylabel('Total Revenue (Miliar Rp)', fontweight='bold')
axes[1].set_title('Total Revenue per Tahun', fontweight='bold')
axes[1].grid(True, alpha=0.3, axis='y')
for i, v in enumerate(yearly_stats['Revenue']/1e9):
    axes[1].text(yearly_stats.index[i], v + v*0.02, f'{v:.2f}B', ha='center', fontweight='bold')

# Total Room Sold per Year
axes[2].bar(yearly_stats.index, yearly_stats['Kamar_Terjual'],
           color='#A23B72', alpha=0.8, edgecolor='black')
axes[2].set_xlabel('Tahun', fontweight='bold')
axes[2].set_ylabel('Total Kamar Terjual', fontweight='bold')
axes[2].set_title('Total Kamar Terjual per Tahun', fontweight='bold')
axes[2].grid(True, alpha=0.3, axis='y')
for i, v in enumerate(yearly_stats['Kamar_Terjual']):
    axes[2].text(yearly_stats.index[i], v + v*0.02, f'{int(v):,}', ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

print("ðŸ“Š Statistik per Tahun:")
print(yearly_stats)

print("\n" + "=" * 80)
print("âœ… EDA SELESAI!")
print("=" * 80)
print(f"\nðŸ’¡ Key Insights:")
print(f"   â€¢ Okupansi rata-rata: {daily_data['Okupansi_Rate'].mean():.2f}%")
print(f"   â€¢ Revenue rata-rata harian: Rp {daily_data['Revenue'].mean():,.0f}")
print(f"   â€¢ Total hari analisis: {len(daily_data)} hari")
print(f"   â€¢ Rentang data: {daily_data['Tanggal'].min().date()} s/d {daily_data['Tanggal'].max().date()}")
print(f"   â€¢ Tipe kamar paling laku: {max(room_totals, key=room_totals.get)} ({max(room_totals.values()):,.0f} kamar)")

# ==================================================================================================
# ðŸ§¹ BLOK 8: Data Cleaning & Validation
# ==================================================================================================
"""
Tahap ini melakukan:
- Cek dan handle duplikasi
- Validasi range nilai
- Handle outliers
- Final data validation
"""

print("\n" + "=" * 80)
print("ðŸ§¹ DATA CLEANING & VALIDATION")
print("=" * 80)

# 1. Cek duplikasi tanggal
print("\n1ï¸âƒ£ Pengecekan Duplikasi Tanggal:")
duplicates = daily_data[daily_data.duplicated(subset=['Tanggal'], keep=False)]
if len(duplicates) > 0:
    print(f"   âš ï¸ Ditemukan {len(duplicates)} tanggal duplikat!")
    print("   Menghapus duplikasi...")
    daily_data = daily_data.drop_duplicates(subset=['Tanggal'], keep='first')
    print(f"   âœ… Setelah cleaning: {len(daily_data)} baris")
else:
    print("   âœ… Tidak ada duplikasi tanggal")

# 2. Validasi range okupansi
print("\n2ï¸âƒ£ Validasi Range Okupansi Rate:")
invalid_okupansi = daily_data[(daily_data['Okupansi_Rate'] < 0) | (daily_data['Okupansi_Rate'] > 100)]
if len(invalid_okupansi) > 0:
    print(f"   âš ï¸ Ditemukan {len(invalid_okupansi)} baris dengan okupansi invalid!")
    print(invalid_okupansi[['Tanggal', 'Okupansi_Rate']])
    daily_data = daily_data[(daily_data['Okupansi_Rate'] >= 0) & (daily_data['Okupansi_Rate'] <= 100)]
    print(f"   âœ… Setelah filtering: {len(daily_data)} baris")
else:
    print("   âœ… Semua nilai okupansi valid (0-100%)")

# 3. Validasi revenue negatif
print("\n3ï¸âƒ£ Validasi Revenue:")
negative_revenue = daily_data[daily_data['Revenue'] < 0]
if len(negative_revenue) > 0:
    print(f"   âš ï¸ Ditemukan {len(negative_revenue)} baris dengan revenue negatif!")
    daily_data = daily_data[daily_data['Revenue'] >= 0]
    print(f"   âœ… Setelah filtering: {len(daily_data)} baris")
else:
    print("   âœ… Semua nilai revenue valid (>= 0)")

# 4. Handle missing values
print("\n4ï¸âƒ£ Pengecekan Missing Values:")
missing_after = daily_data.isnull().sum()
if missing_after.sum() > 0:
    print("   âš ï¸ Ditemukan missing values:")
    print(missing_after[missing_after > 0])
    print("   Mengisi missing values dengan 0 untuk kolom numerik...")
    numeric_cols = daily_data.select_dtypes(include=[np.number]).columns
    daily_data[numeric_cols] = daily_data[numeric_cols].fillna(0)
    print("   âœ… Missing values telah dihandle")
else:
    print("   âœ… Tidak ada missing values")

# 5. Sort by date
print("\n5ï¸âƒ£ Sorting Data by Tanggal:")
daily_data = daily_data.sort_values('Tanggal').reset_index(drop=True)
print("   âœ… Data telah diurutkan berdasarkan tanggal")

# 6. Final validation
print("\n6ï¸âƒ£ Validasi Akhir:")
print(f"   âœ… Total rows: {len(daily_data):,}")
print(f"   âœ… Total columns: {len(daily_data.columns)}")
print(f"   âœ… Date range: {daily_data['Tanggal'].min().date()} to {daily_data['Tanggal'].max().date()}")
print(f"   âœ… No duplicates: {not daily_data.duplicated().any()}")
print(f"   âœ… No missing values: {daily_data.isnull().sum().sum() == 0}")

print("\n" + "=" * 80)
print("âœ… DATA CLEANING SELESAI!")
print("=" * 80)

# ==================================================================================================
# ðŸ”„ BLOK 9: Data Preprocessing & Normalization untuk LSTM
# ==================================================================================================
"""
Tahap ini melakukan:
- Normalisasi data menggunakan MinMaxScaler (0-1)
- Prepare data untuk input LSTM
- Split features yang akan dinormalisasi
"""

print("\n" + "=" * 80)
print("ðŸ”„ DATA PREPROCESSING & NORMALIZATION")
print("=" * 80)

# Kolom yang akan dinormalisasi
cols_to_normalize = [
    'Kamar_Terjual', 'Revenue', 'Okupansi_Rate',
    'Kamar_STD', 'Kamar_SPR', 'Kamar_FMY', 'Kamar_JS'
]

print("\nðŸ“‹ Kolom yang akan dinormalisasi:")
for col in cols_to_normalize:
    print(f"   â€¢ {col}")

# Create copy untuk normalisasi
df_normalized = daily_data.copy()

# Initialize MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

print("\nâ³ Melakukan normalisasi dengan MinMaxScaler...")

# Fit dan transform
df_normalized[cols_to_normalize] = scaler.fit_transform(daily_data[cols_to_normalize])

print("âœ… Normalisasi selesai!")

# Comparison before & after normalization
print("\n" + "=" * 80)
print("ðŸ“Š PERBANDINGAN SEBELUM & SESUDAH NORMALISASI")
print("=" * 80)

comparison_df = pd.DataFrame({
    'Column': cols_to_normalize,
    'Original_Min': [daily_data[col].min() for col in cols_to_normalize],
    'Original_Max': [daily_data[col].max() for col in cols_to_normalize],
    'Normalized_Min': [df_normalized[col].min() for col in cols_to_normalize],
    'Normalized_Max': [df_normalized[col].max() for col in cols_to_normalize]
})

print(comparison_df.to_string(index=False))

# Visualisasi comparison
fig, axes = plt.subplots(2, 2, figsize=(16, 10))

# Okupansi Rate
axes[0, 0].plot(daily_data['Tanggal'], daily_data['Okupansi_Rate'],
               label='Original', alpha=0.7, linewidth=1.5)
axes[0, 0].set_ylabel('Okupansi Rate (%)', fontweight='bold')
axes[0, 0].set_title('Original Data - Okupansi Rate', fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].plot(df_normalized['Tanggal'], df_normalized['Okupansi_Rate'],
               label='Normalized', color='#F18F01', alpha=0.7, linewidth=1.5)
axes[0, 1].set_ylabel('Normalized Value (0-1)', fontweight='bold')
axes[0, 1].set_title('Normalized Data - Okupansi Rate', fontweight='bold')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# Revenue
axes[1, 0].plot(daily_data['Tanggal'], daily_data['Revenue'],
               label='Original', alpha=0.7, linewidth=1.5)
axes[1, 0].set_ylabel('Revenue (Rp)', fontweight='bold')
axes[1, 0].set_title('Original Data - Revenue', fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x/1e6:.1f}M'))

axes[1, 1].plot(df_normalized['Tanggal'], df_normalized['Revenue'],
               label='Normalized', color='#F18F01', alpha=0.7, linewidth=1.5)
axes[1, 1].set_ylabel('Normalized Value (0-1)', fontweight='bold')
axes[1, 1].set_title('Normalized Data - Revenue', fontweight='bold')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\nâœ… Data siap untuk modeling LSTM!")

# ==================================================================================================
# ðŸ’¾ BLOK 10: Export Data Bersih ke Excel
# ==================================================================================================
"""
Tahap ini melakukan:
- Export data yang sudah dibersihkan ke format Excel
- Menyimpan 2 versi: original scale & normalized
- Simpan ke Google Drive
"""

print("\n" + "=" * 80)
print("ðŸ’¾ EXPORT DATA KE EXCEL")
print("=" * 80)

# File paths
output_file_clean = os.path.join(file_path, "2021_2025_Clean.xlsx")
output_file_normalized = os.path.join(file_path, "2021_2025_Clean_Normalized.xlsx")

print("\nâ³ Menyimpan data...")

# Export original clean data
daily_data.to_excel(output_file_clean, index=False, sheet_name='Daily_Data')
print(f"âœ… Original data saved: {os.path.basename(output_file_clean)}")
print(f"   Location: {output_file_clean}")
print(f"   Rows: {len(daily_data):,}")
print(f"   Columns: {len(daily_data.columns)}")

# Export normalized data
df_normalized.to_excel(output_file_normalized, index=False, sheet_name='Normalized_Data')
print(f"\nâœ… Normalized data saved: {os.path.basename(output_file_normalized)}")
print(f"   Location: {output_file_normalized}")
print(f"   Rows: {len(df_normalized):,}")
print(f"   Columns: {len(df_normalized.columns)}")

# Preview final data
print("\n" + "=" * 80)
print("ðŸ‘€ PREVIEW DATA AKHIR (Original Scale)")
print("=" * 80)
print(daily_data.head(10))

print("\n" + "=" * 80)
print("ðŸ‘€ PREVIEW DATA AKHIR (Normalized)")
print("=" * 80)
print(df_normalized.head(10))

# Summary statistics
print("\n" + "=" * 80)
print("ðŸ“Š SUMMARY STATISTICS - FINAL DATA")
print("=" * 80)
print(daily_data[cols_to_normalize].describe().round(2))

print("\n" + "=" * 80)
print("ðŸŽ‰ PROSES SELESAI!")
print("=" * 80)
print("\nâœ… Semua tahapan berhasil diselesaikan:")
print("   1. âœ… Mount Google Drive & Import Libraries")
print("   2. âœ… Identifikasi File SQL")
print("   3. âœ… Verifikasi MD5 Hash")
print("   4. âœ… Load & Parse Data dari SQL")
print("   5. âœ… Initial Data Exploration")
print("   6. âœ… Filter Data untuk Analisis")
print("   7. âœ… Exploratory Data Analysis (EDA)")
print("   8. âœ… Data Cleaning & Validation")
print("   9. âœ… Data Preprocessing & Normalization")
print("   10. âœ… Export Data ke Excel")

print("\nðŸ“‚ File output yang tersedia:")
print(f"   â€¢ {os.path.basename(output_file_clean)}")
print(f"   â€¢ {os.path.basename(output_file_normalized)}")

print("\nðŸš€ Data siap untuk tahap selanjutnya:")
print("   â€¢ Modeling LSTM")
print("   â€¢ Training & Validation")
print("   â€¢ Prediksi Okupansi")
print("   â€¢ Evaluasi Model")

print("\n" + "=" * 80)
